#include "include.h"

namespace Array {
	std::vector<std::string> EmoteNumbers = {
		":zero:",
		":one:",
		":two:",
		":three:",
		":four:",
		":five:",
		":six:",
		":seven:",
		":eight:",
		":nine:"
	};
	
	std::vector<std::string> EmoteAlphabet = {
		":regional_indicator_a:",
		":regional_indicator_b:",
		":regional_indicator_c:",
		":regional_indicator_d:",
		":regional_indicator_e:",
		":regional_indicator_f:",
		":regional_indicator_g:",
		":regional_indicator_h:",
		":regional_indicator_i:",
		":regional_indicator_j:",
		":regional_indicator_k:",
		":regional_indicator_l:",
		":regional_indicator_m:",
		":regional_indicator_n:",
		":regional_indicator_o:",
		":regional_indicator_p:",
		":regional_indicator_q:",
		":regional_indicator_r:",
		":regional_indicator_s:",
		":regional_indicator_t:",
		":regional_indicator_u:",
		":regional_indicator_v:",
		":regional_indicator_w:",
		":regional_indicator_x:",
		":regional_indicator_y:",
		":regional_indicator_z:"
	};

	std::vector<std::string> Conversation8Ball = {
		 "As I see it, yes.",
		 "Ask again later.",
		 "Better not tell you now.",
		 "Cannot predict now.",
		 "Concentrate and ask again.",
		 "Don’t count on it.",
		 "It is certain.",
		 "It is decidedly so.",
		 "Most likely.",
		 "My reply is no.",
		 "My sources say no.",
		 "Outlook not so good.",
		 "Outlook good.",
		 "Reply hazy, try again.",
		 "Signs point to yes.",
		 "Very doubtful.",
		 "Without a doubt.",
		 "Yes.",
		 "Yes – definitely.",
		 "You may rely on it."
	};

	std::vector<std::string> TopReactionFBI = {
		"https://media1.giphy.com/media/QUY2pzDAKVpX3QacCg/giphy.gif?cid=ecf05e4754983de5d6841592b1fd5682ba37020a38d78262&rid=giphy.gif",
		"https://media1.giphy.com/media/LT6GjSh99SGYp5qvhr/giphy.gif?cid=ecf05e4754983de5d6841592b1fd5682ba37020a38d78262&rid=giphy.gif",
		"https://media2.giphy.com/media/kxevHLcRrMbtC1SXa8/giphy.gif?cid=ecf05e4754983de5d6841592b1fd5682ba37020a38d78262&rid=giphy.gif"
	};

	std::vector<std::string> WordFilterList = {
		"4r5e",
		"5h1t",
		"5hit",
		"a55",
		"anal",
		"anus",
		"ar5e",
		"arrse",
		"arse",
		"ass ",
		"ass-fucker",
		"asses",
		"assfucker",
		"assfukka",
		"asshole",
		"assholes",
		"asswhole",
		"a_s_s",
		"b!tch",
		"b00bs",
		"b17ch",
		"b1tch",
		"ballbag",
		"balls",
		"ballsack",
		"bastard",
		"beastial",
		"beastiality",
		"bellend",
		"bestial",
		"bestiality",
		"bi+ch",
		"biatch",
		"bitch",
		"bitcher",
		"bitchers",
		"bitches",
		"bitchin",
		"bitching",
		"bloody",
		"blow job",
		"blowjob",
		"blowjobs",
		"boiolas",
		"bollock",
		"bollok",
		"boner",
		"boob",
		"breasts",
		"buceta",
		"bugger",
		"bunny fucker",
		"butt",
		"butthole",
		"buttmunch",
		"buttplug",
		"c0ck",
		"c0cksucker",
		"carpet muncher",
		"cawk",
		"chink",
		"cipa",
		"cl1t",
		"clit",
		"clitoris",
		"clits",
		"cnut",
		"cock",
		"cock-sucker",
		"cockface",
		"cockhead",
		"cockmunch",
		"cockmuncher",
		"cocks",
		"cocksuck ",
		"cocksucked ",
		"cocksucker",
		"cocksucking",
		"cocksucks ",
		"cocksuka",
		"cocksukka",
		"cokmuncher",
		"coksucka",
		"coon",
		"crap",
		"cum ",
		"cummer",
		"cumming",
		"cums",
		"cumshot",
		"cunilingus",
		"cunillingus",
		"cunnilingus",
		"cunt",
		"cuntlick ",
		"cuntlicker ",
		"cuntlicking ",
		"cunts",
		"cyalis",
		"cyberfuc",
		"cyberfuck ",
		"cyberfucked ",
		"cyberfucker",
		"cyberfuckers",
		"cyberfucking ",
		"d1ck",
		"damn",
		"dick",
		"dickhead",
		"dildo",
		"dildos",
		"dink",
		"dinks",
		"dirsa",
		"dlck",
		"dog-fucker",
		"doggin",
		"dogging",
		"donkeyribber",
		"ejaculate",
		"ejaculated",
		"ejaculates ",
		"ejaculating ",
		"ejaculatings",
		"ejaculation",
		"ejakulate",
		"f u c k",
		"f u c k e r",
		"f4nny",
		"fag",
		"fagging",
		"faggitt",
		"faggot",
		"faggs",
		"fagot",
		"fagots",
		"fags",
		"fanny",
		"fannyflaps",
		"fannyfucker",
		"fanyy",
		"fatass",
		"fcuk",
		"fcuker",
		"fcuking",
		"feck",
		"fecker",
		"felching",
		"fellate",
		"fellatio",
		"fingerfuck ",
		"fingerfucked ",
		"fingerfucker ",
		"fingerfuckers",
		"fingerfucking ",
		"fingerfucks ",
		"fistfuck",
		"fistfucked ",
		"fistfucker ",
		"fistfuckers ",
		"fistfucking ",
		"fistfuckings ",
		"fistfucks ",
		"flange",
		"fook",
		"fooker",
		"fuck",
		"fudge packer",
		"fudgepacker",
		"fuk",
		"fuker",
		"fukker",
		"fukkin",
		"fuks",
		"fukwhit",
		"fukwit",
		"fux",
		"fux0r",
		"f_u_c_k",
		"gangbang",
		"gangbanged ",
		"gangbangs ",
		"gaylord",
		"gaysex",
		"goatse",
		"god-dam",
		"god-damned",
		"goddamn",
		"goddamned",
		"hardcoresex ",
		"hell ",
		"heshe",
		"hoar",
		"hoare",
		"horniest",
		"horny",
		"hotsex",
		"jack-off ",
		"jackoff",
		"jap",
		"jerk-off ",
		"jism",
		"jiz ",
		"jizm ",
		"jizz",
		"kawk",
		"knob",
		"knobead",
		"knobed",
		"knobend",
		"knobhead",
		"knobjocky",
		"knobjokey",
		"kock",
		"kondum",
		"kondums",
		"kum",
		"kummer",
		"kumming",
		"kums",
		"kunilingus",
		"l3i+ch",
		"l3itch",
		"labia",
		"lmfao",
		"lusting",
		"m0f0",
		"m0fo",
		"m45terbate",
		"ma5terb8",
		"ma5terbate",
		"masochist",
		"master-bate",
		"masterb8",
		"masterbat*",
		"masterbat3",
		"masterbate",
		"masterbation",
		"masterbations",
		"masturbate",
		"mo-fo",
		"mof0",
		"mofo",
		"mothafuck",
		"mothafucka",
		"mothafuckas",
		"mothafuckaz",
		"mothafucked ",
		"mothafucker",
		"mothafuckers",
		"mothafuckin",
		"mothafucking ",
		"mothafuckings",
		"mothafucks",
		"mother fucker",
		"motherfuck",
		"motherfucked",
		"motherfucker",
		"motherfuckers",
		"motherfuckin",
		"motherfucking",
		"motherfuckings",
		"motherfuckka",
		"motherfucks",
		"muff",
		"mutha",
		"muthafecker",
		"muthafuckker",
		"muther",
		"mutherfucker",
		"n1gga",
		"n1gger",
		"nazi",
		"nigg3r",
		"nigg4h",
		"nigga",
		"niggah",
		"niggas",
		"niggaz",
		"nigger",
		"niggers ",
		"nig ",
		"nob jokey",
		"nobhead",
		"nobjocky",
		"nobjokey",
		"numbnuts",
		"nutsack",
		"orgasim ",
		"orgasims ",
		"orgasm",
		"orgasms ",
		"p0rn",
		"pawn",
		"pecker",
		"penis",
		"penisfucker",
		"phonesex",
		"phuck",
		"phuk",
		"phuked",
		"phuking",
		"phukked",
		"phukking",
		"phuks",
		"phuq",
		"pigfucker",
		"pimpis",
		"piss ",
		"pissed",
		"pisser",
		"pissers",
		"pisses ",
		"pissflaps",
		"pissin ",
		"pissing",
		"pissoff ",
		"poop",
		"porn",
		"porno",
		"pornography",
		"pornos",
		"prick",
		"pricks ",
		"pron",
		"pube",
		"pusse",
		"pussi",
		"pussies",
		"pussy",
		"pussys ",
		"rectum",
		"retard",
		"rimjaw",
		"rimming",
		"s hit",
		"s.o.b.",
		"sadist",
		"schlong",
		"screwing",
		"scroat",
		"scrote",
		"scrotum",
		"semen",
		"sex ",
		"sh!+",
		"sh!t",
		"sh1t",
		"shag",
		"shagger",
		"shaggin",
		"shagging",
		"shemale",
		"shi+",
		"shit",
		"shitdick",
		"shite",
		"shited",
		"shitey",
		"shitfuck",
		"shitfull",
		"shithead",
		"shiting",
		"shitings",
		"shits",
		"shitted",
		"shitter",
		"shitters ",
		"shitting",
		"shittings",
		"shitty ",
		"skank",
		"slut",
		"smegma",
		"smut",
		"snatch",
		"son-of-a-bitch",
		"spac",
		"spunk",
		"s_h_i_t",
		"t1tt1e5",
		"t1tties",
		"teets",
		"teez",
		"testical",
		"testicle",
		"tit",
		"titfuck",
		"tits",
		"titt",
		"tittie5",
		"tittiefucker",
		"titties",
		"tittyfuck",
		"tittywank",
		"titwank",
		"tosser",
		"turd",
		"tw4t",
		"twat",
		"twathead",
		"twatty",
		"twunt",
		"twunter",
		"v14gra",
		"v1gra",
		"vagina",
		"viagra",
		"vulva",
		"wank",
		"wanker",
		"wanky",
		"whoar",
		"whore",
	};

	std::map<std::string, char> SymbolsFilterList = {
		std::pair<std::string, char>("@", 'a'),
		std::pair<std::string, char>("1", 'i'),
		std::pair<std::string, char>("|", 'i'),
		std::pair<std::string, char>("3", 'e'),
		std::pair<std::string, char>("0", 'o'),
		std::pair<std::string, char>("(", 'c'),
		std::pair<std::string, char>(")", 't')
	};

	std::vector<std::string> FunTalkStr = {
		"We are doing this roast tonight to help %s live out one of his sexual fantasies, to have a room full of his friends shit all over him.",
		"A little known fact is that a long time ago %s used to work at McDonald's. It was the last time anyone said about your work, 'I'm lovin' it.'",
		"This is exciting %s right?? Well tell your face.",
		"%s if laughter is the best medicine, your face must be curing the world.",
		"It's nice to see such a diverse crowd here today. We've got Indians, Jews, Whites, and whatever the fuck %s is.",
		"Welcome to the roast of %s! My only regret is that %s's roast is happening in 2019 in Austin, and not 1945 Germany.",
		"%s's so old and Jewish he attended Shakespeare's bar mitzvah.",
		"%s's so Jewish his tagline on LinkedIn is: 'Once you go Jew, no Christian will do.'",
		"%s's so Jewish and so gay at the synagogue they call him a HeBlew.",
		"%s went to Israel for a month to explore his Jewish heritage. he found out a bunch of new things about his culture. For example, did you know his Hebrew name is 'Yeecchh.'",
		"%s, I heard in Israel everyone spends Saturday at home with their families? That's sweet. But man, your mom nags a lot and can be really challenging and annoying. I feel for you. If I had a mother like that I'd be gay too.",
		"This is a very Jewish neighborhood you live in %s. Even the ATM down the street is Jewish. When I tried to take out some money, it said, 'What did you do with the last $50 I gave you ??'",
		"Of course %s is the center of attention tonight. Dude you're like a Jewish rockstar! What's your band name: Guns & Noses ?",
		"%s is a very religious person. he actually models his life after Jesus. And by that I mean he's a Jew who's only been nailed three times.",
		"But everyone knows our dear friend %s, he‘s like a Jewish rockstar. What band are in, 'I Want My Nickelback?'",
		"Listening to %s's speech tonight answers the question: 'What if Hitler only killed all the funny Jews?'",
		"By the way where's my other Jews at?? Oh nice, we're just two more away from a condo board meeting!",
		"But geez %s you're getting fatter by the day. You're like Honey Jew Jew.",
		"%s's so old he owes Jesus a nickel.",
		"%s's so old one of his favorite memories as a child was taking a boat ride with two of every animal.",
		"%s's so old his prostate is almost the size of his ego.",
		"%s's so old his blood type is Oh-No.",
		"You're such an old fossil already.....%s is so old, that when he was a kid science fiction was a horseless carriage.",
		"%s's definitely showing his age. Backstage I gave him a joint to alleviate his chronic pain, and he rubbed BenGay in it.",
		"%s recently quit his job and now has a lot of free time. he plans on spending his retirement opening a jar.",
		"%s's so old the first porno he watched was a ghost banging some chick named Mary.",
		"%s's so old his balls are starting to look like a tent nobody knows how to fold up.",
		"%s is getting so old he has to take an Aspirin before he jerks off.",
		"You all know %s is my first and most longtime friend I have. What you may not know is that he's also the first and most longtime customer of ProActive Acne Systems.",
		"Good lord this is an ugly group of people. Holy shit, you know the crowd is ugly when we invited %s as eye candy.",
		"And %s you're looking pretty rough this evening. %s looks like if sweatpants were a person.",
		"Getting married to you must've been rough. What was your wedding song? 'How Much Is That Doggy In The Window?'",
		"%s is so ugly he's been the only one ever rejected from Queer Eye for the Straight guy.",
		"%s is so ugly in October when he went to the haunted house they handed his an application.",
		"%s's psychiatrist said he was crazy and he said he wanted a second opinion. The psychiatrist said 'Okay, you're ugly too.'",
		"%s's nose is so big he Apple had to make a custom iPhone that unlocks using Nose ID.",
		"Holy shit don't look now but %s's gotten hairy-er since we started this roast!",
		"%s lost 30 lbs when he joined Weight Watchers, and lost another 10 lbs when we shaved he back.",
		"%s you're so hairy you're making it hard for your parents to choose a wife for you. You look like slumdog million hair.",
		"We all love %s but he definitely is one cheap bastard. For example, he loves watching porno in reverse. I asked him why he did that, and he said, 'I like the part where the hooker gives the money back.'",
		"Me and %s we're talking. I told he you're supposed to spend 2 months salary on an engagement ring. %s was like, 'Dude I'm not gonna spend 2 or 3 hundreds dollars on no engagement ring!'",
		"%s I'm glad you could come today, but will be sad you're leaving early for your side gig driving for Uber.",
		"%s's so cheap he won't even pay attention.",
		"%s's so cheap he complains that penny slots are expensive.",
		"%s's so cheap he won't even tip his hat.",
		"%s is SO stingy the ducks throw bread at him.",
		"I'd like to thank all of you for coming today, and I'd like to thank %s for polishing his head.",
		"I thought we were gathered here today for the Roast of %s. But as I look around at all these attendees, this looks more like a support group for balding men.",
		"But in all seriousness, %s is a great person. his heart is almost big as his bald spot.",
		"On a more serious note....%s, despite all your accomplishments, despite all the businesses you've created, despite all the incomes you've increased, despite all the people you've helped, and despite all the lives you've touched.......you're still going fucking bald.",
		"%s is very hardworking. The only thing not hard working on %s is his hair follicles.",
		"Hey %s I like your haircut. You look like the world's tallest baby.",
		"%s I think it's really cool you go to the same barber as Jeff Bezos.",
		"%s looks like the 'Before' picture on those Hair Club for Men commercials.",
		"%s when are you gonna buy a new outfit??",
		"Everyday you wear the same jeans and same flannel patterned shirt. You're like if Al Borland from Home Improvement learned to program a computer.",
		"The way %s dresses looks like the first half of a commercial for antidepressants.",
		"%s is actually pretty good looking, but has a boring personality. Good looks but boring personality, you're like real life clickbait.",
		"%s has worn the same outfit for like 10 years. Holy shit....the only person who's worn the same clothes longer than you is Bart Simpson.",
		"%s I'm glad you and your dull personality could be here. I'm excited to hear your speech at the wedding. With your personality, I'm sure your speech will combine the thrill of talking, with the excitement of standing there.",
		"%s's outfit was recently featured on the cover of Yawn Magazine.",
		"Holy crap there's a lot of Asian's here tonight. Our friend group looks like the first set of workers on the Transcontinental Railroad.",
		"%s does the worlds hardest job, he's a police sketch artist in China.",
		"%s so Asian he was adopted by Brad and Angelina.",
		"Hey %s, did you hear about that Asian guy that won a beauty contest. Yea, me neither.",
		"Hey %s, why do Asian girls always have small boobs? 'Because only A's are acceptable!'",
		"But don't worry about %s getting too upset about these Asian jokes, he'll have time to calm down. If he starts crying and leaves the party, it'll take him at least 3 hours to back out of the driveway.",
		"But it's ok even if you do have an unplanned baby. In the Asian culture you're allowed to abort the fetus until it graduates from medical school.",
		"%s looks like he was adopted by Brad and Angelina.",
		"%s I dunno where you're from, but I'm assuming your parents met on a raft.",
		"%s is so white MY credit score just went up 80 points.",
		"%s is really an American Dream come true. I'm so happy to finally see a middle aged white person get an opportunity.",
		"And let's welcome %s today, or as the Germans call he: Hitler's Wet Dream.",
		"I was impressed when %s played that guard in Schindler's List.",
		"Hey %s I'm looking around and there is not a lot of diversity here. We're just one more white guy away from a Klan meeting.",
		"But %s you're really looking good nowadays. What %s has lost in weight, he has also GAINED in weight.",
		"But %s you've definitely been packing on the pounds. The last time %s went to the dry cleaners they said, 'We don't do curtains.'",
		"%s I checked your Facebook, and it turns out you used to be a bit chubby. I'm impressed that you've managed to lose so much weight. That's right, %s lost 30 pounds on Nutrisystem, and another 10 when he shaved his back.",
		"Backstage before this speech I rolled a gigantic fatty. Because that was the only way we could get %s on to the stage.",
		"%s so fat and lazy the only exercise he gets is when his Restless Leg Syndrome starts flaring up.",
		"Your family told me they regret they couldn't' be here tonight, but they did send 4 bags of grain.",
		"%s you look like if the fat kid from Stranger Things wished he was big.",
		"The church didn't accept %s's gay lifestyle. So he started his own religion: The Church of Latter Day Taints. It's like a normal church, except you're happy when the priest fucks you.",
		"Me and %s are really good friends but we've had our ups and downs, one time %s actually tried to sue me for $10,000. I got really defensive and was like 'You're suing me for $10,000?? Fuck you...you can suck my dick.' and %s was like, 'well OK if you want to settle out of court.'",
		"Me and %s are good friends and we hangout a lot. And some people have even suspected we were gay or something. But that's not true. We like hanging out and discussing manly guy stuff. Like one time I asked him, '%s, tell me about your first blowjob, what was it like?' And he said 'oh man, it tasted awful.'",
		"When I heard that %s finally came out of the closet I wasn't really surprised....dude you're so gay MY ass hurts.",
		"I once asked %s why he dresses so flamboyantly and he got upset and hit me with his purse.",
		"I'm having a pretty good time at this roast, but I'm really disappointed with this venue.....I was hoping we could have dinner at a location with a lot more space...like %s's asshole.",
		"%s – I'm glad you got taken off of the party planning committee, if it were up to you, we'd all be watching showtunes, male strippers, or those two fruitcakes with the white tiger.",
		"Actually the last time me and %s hung out it ended kind of weird. We were gonna smoke weed together. I asked if he had papers, and he just ran off.",
		"Hey %s, why was Hellen Keller such a bad driver? Because she's a woman.",
		"Hey %s, why do Japanese people have such squinty eyes? Because atomic bombs are hella bright."
		"This group is literally Hitler's wet dream. It's got Jews, Indians, Russians, and whatever the fuck %s is.'",
		"I wanna everyone for coming to this roast. My one complaint is next time that we have dinner in some place much larger, like %s's pussy."
	};
}